### ISSUE TITLE
Pretrained weights links are broken

### ISSUE THREAD

**Issue by debugmenot** [yh-pengtu/FemtoDet#14]
Hi guys! Have some issues with training setup. First of all the pretrained weights links to pan.baidu are broken (not. valid anymore).
When trying to train from scratch, replacing model.backbone.init_cfg to None getting dimension errors:

2023-11-18 03:15:07,836 - mmdet - INFO - workflow: [('train', 1)], max: 300 epochs
2023-11-18 03:15:07,839 - mmdet - INFO - Checkpoints will be saved to /Users/anykey/FemtoDet/work_dirs/femtodet_0stage by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 220, in <module>
    main()
  File "tools/train.py", line 209, in main
    train_detector(
  File "/Users/anykey/FemtoDet/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 52, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/Users/anykey/FemtoDet/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/Users/anykey/FemtoDet/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/Users/anykey/FemtoDet/mmdet/models/detectors/yolox.py", line 95, in forward_train
    losses = super(YOLOX, self).forward_train(img, img_metas, gt_bboxes,
  File "/Users/anykey/FemtoDet/mmdet/models/detectors/single_stage.py", line 82, in forward_train
    x = self.extract_feat(img)
  File "/Users/anykey/FemtoDet/mmdet/models/detectors/single_stage.py", line 43, in extract_feat
    x = self.backbone(img)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/anykey/FemtoDet/mmdet/models/backbones/femtonet.py", line 274, in forward
    x = self.conv1(x)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 201, in forward
    x = self.conv(x)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 8, 3, 640, 640]

Please help, very interested in testing your model.

**Comment by yh-pengtu** [comment]
May other issues within this repo can give u some cues. I’m on holidays, hope u everything will be ok~ 
    
        
            
                
                    
                        
                    
                    
                        
                            Peng.T
                            
                            
                        
                    
                
            
        
    
---- Replied Message ***@***.***>Date11/18/2023 06:37 ***@***.***> ***@***.***>Subject[yh-pengtu/FemtoDet] Pretrained weights links are broken (Issue #14)
Hi guys! Have some issues with training setup. First of all the pretrained weights links to pan.baidu are broken (not. valid anymore).
When trying to train from scratch, replacing model.backbone.init_cfg to None getting dimension errors:
2023-11-18 03:15:07,836 - mmdet - INFO - workflow: [('train', 1)], max: 300 epochs
2023-11-18 03:15:07,839 - mmdet - INFO - Checkpoints will be saved to /Users/anykey/FemtoDet/work_dirs/femtodet_0stage by HardDiskBackend.
Traceback (most recent call last):
File "tools/train.py", line 220, in 
main()
File "tools/train.py", line 209, in main
train_detector(
File "/Users/anykey/FemtoDet/mmdet/apis/train.py", line 208, in train_detector
runner.run(data_loaders, cfg.workflow)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
epoch_runner(data_loaders[i], **kwargs)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
self.run_iter(data_batch, train_mode=True, **kwargs)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
outputs = self.model.train_step(data_batch, self.optimizer,
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 52, in train_step
return self.module.train_step(*inputs[0], **kwargs[0])
File "/Users/anykey/FemtoDet/mmdet/models/detectors/base.py", line 248, in train_step
losses = self(**data)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
return old_func(*args, **kwargs)
File "/Users/anykey/FemtoDet/mmdet/models/detectors/base.py", line 172, in forward
return self.forward_train(img, img_metas, **kwargs)
File "/Users/anykey/FemtoDet/mmdet/models/detectors/yolox.py", line 95, in forward_train
losses = super(YOLOX, self).forward_train(img, img_metas, gt_bboxes,
File "/Users/anykey/FemtoDet/mmdet/models/detectors/single_stage.py", line 82, in forward_train
x = self.extract_feat(img)
File "/Users/anykey/FemtoDet/mmdet/models/detectors/single_stage.py", line 43, in extract_feat
x = self.backbone(img)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/Users/anykey/FemtoDet/mmdet/models/backbones/femtonet.py", line 274, in forward
x = self.conv1(x)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 201, in forward
x = self.conv(x)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
return self._conv_forward(input, self.weight, self.bias)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 8, 3, 640, 640]
Please help, very interested in testing your model.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yh-pengtu/FemtoDet/issues/14",
"url": "https://github.com/yh-pengtu/FemtoDet/issues/14",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yh-pengtu** [comment]
Try this link to download the missed pretrained weight: https://pan.baidu.com/s/1JGsvlvzPkb5nxGBaRSD7ng?pwd=hx8k 提取码：hx8k 
    
        
            
                
                    
                        
                    
                    
                        
                            Peng.T
                            
                            
                        
                    
                
            
        
    
---- Replied Message ***@***.***>Date11/18/2023 06:37 ***@***.***> ***@***.***>Subject[yh-pengtu/FemtoDet] Pretrained weights links are broken (Issue #14)
Hi guys! Have some issues with training setup. First of all the pretrained weights links to pan.baidu are broken (not. valid anymore).
When trying to train from scratch, replacing model.backbone.init_cfg to None getting dimension errors:
2023-11-18 03:15:07,836 - mmdet - INFO - workflow: [('train', 1)], max: 300 epochs
2023-11-18 03:15:07,839 - mmdet - INFO - Checkpoints will be saved to /Users/anykey/FemtoDet/work_dirs/femtodet_0stage by HardDiskBackend.
Traceback (most recent call last):
File "tools/train.py", line 220, in 
main()
File "tools/train.py", line 209, in main
train_detector(
File "/Users/anykey/FemtoDet/mmdet/apis/train.py", line 208, in train_detector
runner.run(data_loaders, cfg.workflow)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
epoch_runner(data_loaders[i], **kwargs)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
self.run_iter(data_batch, train_mode=True, **kwargs)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
outputs = self.model.train_step(data_batch, self.optimizer,
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 52, in train_step
return self.module.train_step(*inputs[0], **kwargs[0])
File "/Users/anykey/FemtoDet/mmdet/models/detectors/base.py", line 248, in train_step
losses = self(**data)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
return old_func(*args, **kwargs)
File "/Users/anykey/FemtoDet/mmdet/models/detectors/base.py", line 172, in forward
return self.forward_train(img, img_metas, **kwargs)
File "/Users/anykey/FemtoDet/mmdet/models/detectors/yolox.py", line 95, in forward_train
losses = super(YOLOX, self).forward_train(img, img_metas, gt_bboxes,
File "/Users/anykey/FemtoDet/mmdet/models/detectors/single_stage.py", line 82, in forward_train
x = self.extract_feat(img)
File "/Users/anykey/FemtoDet/mmdet/models/detectors/single_stage.py", line 43, in extract_feat
x = self.backbone(img)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/Users/anykey/FemtoDet/mmdet/models/backbones/femtonet.py", line 274, in forward
x = self.conv1(x)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 201, in forward
x = self.conv(x)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
return self._conv_forward(input, self.weight, self.bias)
File "/opt/homebrew/Caskroom/miniconda/base/envs/femtodet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 8, 3, 640, 640]
Please help, very interested in testing your model.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yh-pengtu/FemtoDet/issues/14",
"url": "https://github.com/yh-pengtu/FemtoDet/issues/14",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
