### ISSUE TITLE
权重文件的百度网盘分享链接已经过期

### ISSUE THREAD

**Issue by little-spoon** [yh-pengtu/FemtoDet#7]
您好，我想请问一下在训练此模型的时候必须要使用`pretrain_weight`吗？
但是你们分享的百度网盘链接已经过期了，能否延长它的有效期呢？
如果这个可以不使用预训练权重的话，是否直接 `pretrain_weigth = None` 就可以了呢？但似乎这么做了以后会报类型错误，如下：
```
Traceback (most recent call last):
  File "./tools/train.py", line 220, in <module>
    main()
  File "./tools/train.py", line 194, in main
    model.init_weights()
  File "/home/host/mounted2/anaconda3/envs/mm-new/lib/python3.7/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
    m.init_weights()
  File "/home/host/mounted2/anaconda3/envs/mm-new/lib/python3.7/site-packages/mmcv/runner/base_module.py", line 106, in init_weights
    initialize(self, self.init_cfg)
  File "/home/host/mounted2/anaconda3/envs/mm-new/lib/python3.7/site-packages/mmcv/cnn/utils/weight_init.py", line 636, in initialize
    _initialize(module, cp_cfg)
  File "/home/host/mounted2/anaconda3/envs/mm-new/lib/python3.7/site-packages/mmcv/cnn/utils/weight_init.py", line 539, in _initialize
    func(module)
  File "/home/host/mounted2/anaconda3/envs/mm-new/lib/python3.7/site-packages/mmcv/cnn/utils/weight_init.py", line 520, in __call__
    self.prefix, self.checkpoint, map_location=self.map_location)
  File "/home/host/mounted2/anaconda3/envs/mm-new/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 593, in _load_checkpoint_with_prefix
    checkpoint = _load_checkpoint(filename, map_location=map_location)
  File "/home/host/mounted2/anaconda3/envs/mm-new/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 572, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/host/mounted2/anaconda3/envs/mm-new/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 310, in load_checkpoint
    checkpoint_loader = cls._get_checkpoint_loader(filename)
  File "/home/host/mounted2/anaconda3/envs/mm-new/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 287, in _get_checkpoint_loader
    if re.match(p, path) is not None:
  File "/home/host/mounted2/anaconda3/envs/mm-new/lib/python3.7/re.py", line 175, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

```

**Comment by yhpengtu** [comment]
May you can try this link again (https://pan.baidu.com/s/1JGsvlvzPkb5nxGBaRSD7ng?pwd=hx8k 提取码：hx8k)

**Comment by little-spoon** [comment]
Done. Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yh-pengtu/FemtoDet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月17日(星期二) 晚上9:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yh-pengtu/FemtoDet] 权重文件的百度网盘分享链接已经过期 (Issue #7)





 
May you can try this link again (https://pan.baidu.com/s/1JGsvlvzPkb5nxGBaRSD7ng?pwd=hx8k 提取码：hx8k)
